# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-06 14:02
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author_image', models.ImageField(blank=True, help_text='250x25', null=True, upload_to='img/', verbose_name='\u0424\u043e\u0442\u043e \u0430\u0432\u0442\u043e\u0440\u0430')),
            ],
            options={
                'db_table': 'author',
                'verbose_name': '\u0410\u0432\u0442\u043e\u0440',
                'verbose_name_plural': '\u0410\u0432\u0442\u043e\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u0411\u0440\u0435\u043d\u0434\u044b')),
            ],
            options={
                'db_table': 'brands',
                'verbose_name': '\u0411\u0440\u0435\u043d\u0434',
                'verbose_name_plural': '\u0411\u0440\u0435\u043d\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='my_magazine.Category', verbose_name='\u0420\u041e\u0414\u0418\u0422\u0415\u041b\u042c\u0421\u041a\u0418\u0419 \u043a\u043b\u0430\u0441\u0441')),
            ],
            options={
                'ordering': ('tree_id', 'level'),
                'db_table': 'category',
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f')),
                ('comments_date', models.DateField(auto_now=True, verbose_name='date')),
                ('comments_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(blank=True, max_length=200, null=True)),
                ('home_text', tinymce.models.HTMLField(blank=True, null=True)),
                ('home_date', models.DateField(blank=True, null=True)),
                ('home_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='\u0412\u0438\u0434\u0435\u043e')),
            ],
            options={
                'db_table': 'home',
                'verbose_name': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0438',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('product_price', models.CharField(max_length=200, verbose_name='\u0426\u0435\u043d\u0430')),
                ('product_img', models.ImageField(blank=True, help_text='350x200', null=True, upload_to='img/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f')),
                ('product_video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='\u0412\u0438\u0434\u0435\u043e')),
                ('product_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('product_like', models.IntegerField(default=0)),
                ('product_stock', models.PositiveIntegerField(verbose_name='\u041d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435')),
                ('product_available', models.BooleanField(default=True, verbose_name='\u0414\u043e\u0441\u0442\u0443\u043f\u0435\u043d')),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='my_magazine.Author', verbose_name='\u0418\u043c\u044f \u0430\u0432\u0442\u043e\u0440')),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', related_query_name='brands', to='my_magazine.Brands', verbose_name='\u0411\u0440\u0435\u043d\u0434\u044b')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='my_magazine.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0442\u043e\u0432\u0430\u0440\u0430')),
            ],
            options={
                'ordering': ['-product_title'],
                'db_table': 'product',
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_magazine.Product'),
        ),
    ]
