# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-08 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u041f\u043e\u0438\u0441\u043a \u043f\u043e \u0441\u0430\u0439\u0442\u0443:')),
            ],
            options={
                'db_table': 'keywords',
                'verbose_name': '\u0422\u0435\u0433\u0438',
                'verbose_name_plural': '\u0422\u0435\u0433\u0438',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keyword', to='my_magazine.Keywords', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
